version: '2.3'
services:
  xserver:
    build: ./xserver
    image: wn1980/xserver
    container_name: ros_xserver
    restart: unless-stopped
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3000:6900"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  simulator:
    image: devrt/simulator-turtlesim
    container_name: ros_simulator
    restart: unless-stopped
    ipc: host
    security_opt:
    - seccomp:unconfined
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    depends_on:
    - xserver
  workspace:
    # env_file:
    #   - .env
    image: devrt/ros-devcontainer-vscode:melodic-desktop
    container_name: ros_workspace
    restart: unless-stopped
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3001:3000"
    - "3002:8888"
    volumes:
    - workspace:/workspace
    - ~/.gitconfig:/home/developer/.gitconfig
    environment:
    - DISPLAY=:0
    - ROS_MASTER_URI=http://simulator:11311/
    volumes_from:
    - xserver
    - simulator
    depends_on:
    - xserver
  web:
    build: ./html
    image: wn1980/webserver
    container_name: ros_webserver
    restart: unless-stopped
    depends_on:
    - workspace
    ports:
    - "8080:80"
volumes:
  workspace:
