version: '2.4'

services:

  xserver:
    #build: ./xserver
    image: wn1980/xserver
    container_name: ros_xserver
    init: true
    restart: unless-stopped
    #ipc: host
    security_opt:
      - seccomp:unconfined
    volumes:
        - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3000:6901"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20

  master:
      build: ./master
      image: wn1980/master
      container_name: ros_master
      init: true
      restart: unless-stopped
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      ports:
        - "9090:9090"
        - "11311:11311"

  simulator:
    build: ./turtlebot2
    image: wn1980/simulator
    #image: devrt/simulator-turtlebot3
    container_name: ros_simulator
    init: true
    restart: "no"
    #ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://master:11311
    volumes_from:
      - xserver
    depends_on:
      - xserver
      - master

  workspace:
    # env_file:
    #   - .env
    build: ./workspace
    image: wn1980/workspace
    container_name: ros_workspace
    hostname: ros-ops
    init: true
    restart: unless-stopped
    #ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3000"
      - "3002:8888"
    volumes:
      - workspace:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://master:11311
    volumes_from:
      - xserver
    #    - simulator
    depends_on:
      - xserver
      - master

  web:
    build: ./web
    image: wn1980/webserver
    container_name: ros_webserver
    init: true
    restart: unless-stopped
    depends_on:
      - workspace
    ports:
      - "8080:80"

volumes:
  workspace:
